### ISSUE TITLE
IdentityServer4.AccessTokenValidation update to 1.0.1-rc4 causes 500 on resource server

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4.AccessTokenValidation#36]
```
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            IdentityServerAuthenticationOptions identityServerValidationOptions = new IdentityServerAuthenticationOptions
            {
                Authority = "https://localhost:44318/",
                AllowedScopes = new List<string> {"dataEventRecords"},
                ApiSecret = "dataEventRecordsSecret",
                AutomaticAuthenticate = true,
                SupportedTokens = SupportedTokens.Both,
                // TokenRetriever = _tokenRetriever,
                // required if you want to return a 403 and not a 401 for forbidden responses

                AutomaticChallenge = true,
                
            };

            app.UseIdentityServerAuthentication(identityServerValidationOptions);
```

**Comment by damienbod** [comment]
System.InvalidOperationException: You must either set a ScopeName or set an introspection HTTP handler
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware..ctor(RequestDelegate next, IOptions`1 options, UrlEncoder urlEncoder, ILoggerFactory loggerFactory, IDistributedCache cache)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddleware..ctor(RequestDelegate next, IApplicationBuilder app, CombinedAuthenticationOptions options, ILogger`1 logger)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass3_0.b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by leastprivilege** [comment]
you need to set the ApiName

**Comment by leastprivilege** [comment]
the exception message is wrong though.

**Comment by damienbod** [comment]
thanks

**Comment by leastprivilege** [comment]
Thats only needed for introspection though

**Comment by damienbod** [comment]
Problem comes from the https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection
If you want, I could fix this and do a pull request

Greetings Damien

**Comment by brockallen** [comment]
Fixed by validating that if one is set that the other also needs to be set.

**Comment by damienbod** [comment]
@brockallen Why did you close this, bug is that the Exception message in incorrect as @leastprivilege said.

**Comment by brockallen** [comment]
We fixed the message on the dev branch

**Comment by damienbod** [comment]
@leastprivilege @brockallen   Also noticed that you re-implemented my pull request yourself, why ClientId and not ApiName, otherwise the user will not know that the ApiName needs to be set.

**Comment by leastprivilege** [comment]
we do the error handling now in the top level middleware. In the middle of releasing rc4-update1. Will start to make more sense in an hour ;)M

**Comment by damienbod** [comment]
ah ok, thanks for the feedback

Greetings Damien
