### ISSUE TITLE
AddIdentityServerAuthentication throws MissingMethodException with IdentityModel.AspNetCore.OAuth2Introspection 3.0.0-rc2

### ISSUE THREAD

**Issue by draganjovanovic1** [IdentityServer/IdentityServer4.AccessTokenValidation#84]
I am using IdentityServer4.AccessTokenValidation 2.0.0-rc1 and it works fine with IdentityModel.AspNetCore.OAuth2Introspection 3.0.0-rc1 but with 3.0.0-rc2 I am getting MissingMethodException. 

Workaround is to fix IdentityModel.AspNetCore.OAuth2Introspection version to 3.0.0-rc1.

```
Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Authentication.AuthenticationBuilder Microsoft.Extensions.DependencyInjection.OAuth2IntrospectionExtensions.AddOAuth2Introspection(Microsoft.AspNetCore.Authentication.AuthenticationBuilder, System.String, System.String, System.Action`1<Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions>)'.
   at Microsoft.AspNetCore.Builder.IdentityServerAuthenticationExtensions.AddIdentityServerAuthentication(AuthenticationBuilder builder, String authenticationScheme, Action`1 configureOptions)
   at ApiF.Program.Startup.ConfigureServices(IServiceCollection services) in /Users/dragan/Projects/IdentityServer4Playground/apif/Program.fs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ApiF.Program.main(String[] _arg1) in /Users/dragan/Projects/IdentityServer4Playground/apif/Program.fs:line 79
```

**Comment by leastprivilege** [comment]
Final version is released now...

**Comment by draganjovanovic1** [comment]
Thanks. Tested, works good. :thumbsup:
